---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ dependencies_packages }}"
    state: present
    force: true
    update_cache: yes
  register: package_ok
  retries: 5
  delay: 2
  until: package_ok is success

- name: Execute mongo version to capture output
  command: "mongo --version"
  register: mongo_current_version
  changed_when: false
  failed_when: false

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: "{{ mongo_gpg_key }}"
    state: present

- name: Add Mongo Repository
  ansible.builtin.apt_repository:
    repo: "{{ mongo_apt_repository }}"
    state: present

- name: Set mongo_version
  ansible.builtin.set_fact:
    mongo_packages: "{{ mongo_packages | map('regex_replace', '$', '=' + mongo_version) }}"
  when: mongo_version|length > 0

- name: Install Mongo
  ansible.builtin.apt:
    name: "{{ mongo_packages }}"
    state: present
    force: true
    update_cache: yes
  register: package_ok
  retries: 5
  delay: 2
  until: package_ok is success
  when: >
    (mongo_current_version.rc != 0) or
    (mongo_version not in mongo_current_version.stdout)