---

- name: Execute mongo version to capture output
  ansible.builtin.command: "mongo --version"
  register: mongo_current_version
  changed_when: false
  failed_when: false

- name: Remove Mongo
  ansible.builtin.apt:
    name: "{{ mongo_packages }}"
    state: absent
  retries: 5
  delay: 2
  when: mongo_current_version.rc == 0

- name: Remove Apt signing key
  ansible.builtin.apt_key:
    url: "{{ mongo_gpg_key }}"
    state: absent

- name: Remove Repository
  ansible.builtin.apt_repository:
    repo: "{{ mongo_apt_repository }}"
    state: absent