---
- name: Remove Mongo
  ansible.builtin.apt:
    name: "{{ mongo_packages }}"
    state: absent
    force: true
    update_cache: yes
  retries: 5
  delay: 2

- name: Remove Apt signing key
  ansible.builtin.apt_key:
    url: "{{ mongo_gpg_key }}"
    state: absent

- name: Remove Repository
  ansible.builtin.apt_repository:
    repo: "{{ mongo_apt_repository }}"
    state: absent